#include "TGeoManager.h"
#include "TGeoElement.h"

#include <iostream>
#include <iomanip>
#include <fstream>

const char* destination = "../../includes/StaticNuclearTable.hh";

void dump_masses(std::ostream& os, int maxZ = 7, int maxA = 14) {
	TGeoManager geom("geom", "Nuclide lookup");
	auto* table = geom.GetElementTable();
	
	const auto now = std::time(nullptr);
	os << std::setprecision(17);
	os << "#pragma once\n\n"
		"#include <cstdint>\n"
		"#include <limits>\n\n"
		"/* This file was autogenerated by `dump_masses`\n * from `create_static_nuc_mass_table.cc` program on "
		<< std::put_time(
			std::localtime(&now),
			"%H:%M:%S %d %b %Y"
		) << " */\n"
		<< "namespace phy {\n\n"
		"template<std::uint32_t A, std::uint32_t Z>\n"
		"constexpr double mass() noexcept {\n"
		"  static_assert(A == A+1,\n"
		"    \"No nuclear mass entry available for this (A,Z)\");\n"
		"  return 0;\n"
		"};\n\n"
	;
	for(int Z = 1; Z <= maxZ; ++Z) {
		for(int A = Z; A <= maxA; ++A) {
			const auto* nuclide = table->GetElementRN(A, Z);
			if(!nuclide)
				continue;

			const double mass = A * 931.49410242 + nuclide->MassEx();

			os << "template<> inline constexpr double mass<"
				<< A << ',' << Z << ">() noexcept { return " << mass << "; }\n";
		}
	}
	os << '\n' <<
		"inline constexpr std::uint64_t nuclide_key(\n"
		"  std::uint32_t A, std::uint32_t Z\n"
		") noexcept {\n"
		"  return (std::uint64_t{A} << 32) | Z;\n"
		"}\n";
	os << "\n"
		<< "inline constexpr double mass(\n"
			"  std::uint32_t A, std::uint32_t Z\n"
			") noexcept {\n"
			"  switch(nuclide_key(A,Z)) {\n";
			
	for(int Z = 1; Z <= maxZ; ++Z) {
		for(int A = Z; A <= maxA; ++A) {
			const auto* nuclide = table->GetElementRN(A, Z);
			if(!nuclide)
				continue;

			const double mass = A * 931.49410242 + nuclide->MassEx();
			os << "    case nuclide_key(" << A << ',' << Z << "): "
				<< "return mass<" << A << ',' << Z << ">();\n";
		}
	}
	os << "    default: return std::numeric_limits<double>::quiet_NaN();\n"
		"  }\n"
		"}\n";
	os << "\n} // namespace phy";
}

int main() {
	std::ofstream ifs{destination};
	dump_masses(ifs);
	std::cout << "\n\n~~~ Written to file: " << destination << "\n";
}
