OPTIMIZATION = 1

ifneq ($(OPTIMIZATION),1)
CXXFLAGS += -ggdb -g3 -O0
#CXXFLAGS += -DANALYSIS_SINGLETHREADED
else
CXXFLAGS += -O3 -march=native
CXXFLAGS += -DANALYSIS_SINGLETHREADED
endif

#CXXFLAGS +=  -std=c++20 
#CXXFLAGS += -Wno-cpp
