#pragma once

#include <cstdint>
#include <limits>

/* This file was autogenerated by `dump_masses`
 * from `create_static_nuc_mass_table.cc` program on 17:00:26 10 Sep 2026 */
namespace phy {

template<std::uint32_t A, std::uint32_t Z>
constexpr double mass() noexcept {
  static_assert(A != A,
    "No nuclear mass entry available for this (A,Z)");
  return 0;
};

template<> inline constexpr double mass<1,1>() noexcept { return 938.78310241999998; }
template<> inline constexpr double mass<2,1>() noexcept { return 1876.1242048399999; }
template<> inline constexpr double mass<3,1>() noexcept { return 2809.43230726; }
template<> inline constexpr double mass<4,1>() noexcept { return 3751.9784096799999; }
template<> inline constexpr double mass<3,2>() noexcept { return 2809.4133072600002; }
template<> inline constexpr double mass<4,2>() noexcept { return 3728.4013096799999; }
template<> inline constexpr double mass<5,2>() noexcept { return 4668.8565121000001; }
template<> inline constexpr double mass<6,2>() noexcept { return 5606.5586145200004; }
template<> inline constexpr double mass<7,2>() noexcept { return 6546.5687169399998; }
template<> inline constexpr double mass<8,2>() noexcept { return 7483.5508193599999; }
template<> inline constexpr double mass<9,2>() noexcept { return 8424.2659217799992; }
template<> inline constexpr double mass<4,3>() noexcept { return 3751.2964096800001; }
template<> inline constexpr double mass<5,3>() noexcept { return 4669.1495120999998; }
template<> inline constexpr double mass<6,3>() noexcept { return 5603.0506145200006; }
template<> inline constexpr double mass<7,3>() noexcept { return 6535.3667169400005; }
template<> inline constexpr double mass<8,3>() noexcept { return 7472.8978193599996; }
template<> inline constexpr double mass<9,3>() noexcept { return 8408.4009217799994; }
template<> inline constexpr double mass<10,3>() noexcept { return 9348.3860241999992; }
template<> inline constexpr double mass<11,3>() noexcept { return 10287.22312662; }
template<> inline constexpr double mass<6,4>() noexcept { return 5607.3396145200004; }
template<> inline constexpr double mass<7,4>() noexcept { return 6536.2287169400006; }
template<> inline constexpr double mass<8,4>() noexcept { return 7456.8945193600002; }
template<> inline constexpr double mass<9,4>() noexcept { return 8394.7949217799996; }
template<> inline constexpr double mass<10,4>() noexcept { return 9327.5480241999994; }
template<> inline constexpr double mass<11,4>() noexcept { return 10266.60912662; }
template<> inline constexpr double mass<12,4>() noexcept { return 11203.00622904; }
template<> inline constexpr double mass<13,4>() noexcept { return 12144.58133146; }
template<> inline constexpr double mass<14,4>() noexcept { return 13080.79943388; }
template<> inline constexpr double mass<7,5>() noexcept { return 6548.3267169400006; }
template<> inline constexpr double mass<8,5>() noexcept { return 7474.8738193600002; }
template<> inline constexpr double mass<9,5>() noexcept { return 8395.8629217799989; }
template<> inline constexpr double mass<10,5>() noexcept { return 9326.9920241999989; }
template<> inline constexpr double mass<11,5>() noexcept { return 10255.103126619999; }
template<> inline constexpr double mass<12,5>() noexcept { return 11191.298229040001; }
template<> inline constexpr double mass<13,5>() noexcept { return 12125.98533146; }
template<> inline constexpr double mass<14,5>() noexcept { return 13064.581433880001; }
template<> inline constexpr double mass<8,6>() noexcept { return 7487.04681936; }
template<> inline constexpr double mass<9,6>() noexcept { return 8412.3609217800004; }
template<> inline constexpr double mass<10,6>() noexcept { return 9330.6400242; }
template<> inline constexpr double mass<11,6>() noexcept { return 10257.085126619999; }
template<> inline constexpr double mass<12,6>() noexcept { return 11177.929229040001; }
template<> inline constexpr double mass<13,6>() noexcept { return 12112.548331460001; }
template<> inline constexpr double mass<14,6>() noexcept { return 13043.93733388; }
template<> inline constexpr double mass<10,7>() noexcept { return 9354.6400242; }
template<> inline constexpr double mass<11,7>() noexcept { return 10271.396126619999; }
template<> inline constexpr double mass<12,7>() noexcept { return 11195.267229040001; }
template<> inline constexpr double mass<13,7>() noexcept { return 12114.76883146; }
template<> inline constexpr double mass<14,7>() noexcept { return 13043.780833880001; }

inline constexpr std::uint64_t nuclide_key(
  std::uint32_t A, std::uint32_t Z
) noexcept {
  return (std::uint64_t{A} << 32) | Z;
}

inline constexpr double mass(
  std::uint32_t A, std::uint32_t Z
) noexcept {
  switch(nuclide_key(A,Z)) {
    case nuclide_key(1,1): return mass<1,1>();
    case nuclide_key(2,1): return mass<2,1>();
    case nuclide_key(3,1): return mass<3,1>();
    case nuclide_key(4,1): return mass<4,1>();
    case nuclide_key(3,2): return mass<3,2>();
    case nuclide_key(4,2): return mass<4,2>();
    case nuclide_key(5,2): return mass<5,2>();
    case nuclide_key(6,2): return mass<6,2>();
    case nuclide_key(7,2): return mass<7,2>();
    case nuclide_key(8,2): return mass<8,2>();
    case nuclide_key(9,2): return mass<9,2>();
    case nuclide_key(4,3): return mass<4,3>();
    case nuclide_key(5,3): return mass<5,3>();
    case nuclide_key(6,3): return mass<6,3>();
    case nuclide_key(7,3): return mass<7,3>();
    case nuclide_key(8,3): return mass<8,3>();
    case nuclide_key(9,3): return mass<9,3>();
    case nuclide_key(10,3): return mass<10,3>();
    case nuclide_key(11,3): return mass<11,3>();
    case nuclide_key(6,4): return mass<6,4>();
    case nuclide_key(7,4): return mass<7,4>();
    case nuclide_key(8,4): return mass<8,4>();
    case nuclide_key(9,4): return mass<9,4>();
    case nuclide_key(10,4): return mass<10,4>();
    case nuclide_key(11,4): return mass<11,4>();
    case nuclide_key(12,4): return mass<12,4>();
    case nuclide_key(13,4): return mass<13,4>();
    case nuclide_key(14,4): return mass<14,4>();
    case nuclide_key(7,5): return mass<7,5>();
    case nuclide_key(8,5): return mass<8,5>();
    case nuclide_key(9,5): return mass<9,5>();
    case nuclide_key(10,5): return mass<10,5>();
    case nuclide_key(11,5): return mass<11,5>();
    case nuclide_key(12,5): return mass<12,5>();
    case nuclide_key(13,5): return mass<13,5>();
    case nuclide_key(14,5): return mass<14,5>();
    case nuclide_key(8,6): return mass<8,6>();
    case nuclide_key(9,6): return mass<9,6>();
    case nuclide_key(10,6): return mass<10,6>();
    case nuclide_key(11,6): return mass<11,6>();
    case nuclide_key(12,6): return mass<12,6>();
    case nuclide_key(13,6): return mass<13,6>();
    case nuclide_key(14,6): return mass<14,6>();
    case nuclide_key(10,7): return mass<10,7>();
    case nuclide_key(11,7): return mass<11,7>();
    case nuclide_key(12,7): return mass<12,7>();
    case nuclide_key(13,7): return mass<13,7>();
    case nuclide_key(14,7): return mass<14,7>();
    default: return std::numeric_limits<double>::quiet_NaN();
  }
}

} // namespace phy